package com.example.service;

import org.springframework.stereotype.Service;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Service for converting Excel files to PDF format
 * Supports multiple conversion strategies
 */
@Service
public class ExcelToPdfConverter {
    
    /**
     * Convert Excel byte array to PDF using available conversion method
     * 
     * @param excelData Excel file as byte array
     * @return PDF as byte array
     * @throws IOException if conversion fails
     */
    public byte[] convertToPdf(byte[] excelData) throws IOException {
        // Try LibreOffice first (best quality)
        if (isLibreOfficeAvailable()) {
            return convertUsingLibreOffice(excelData);
        }
        
        // Fallback: Return instruction PDF
        return createInstructionPdf(excelData);
    }
    
    /**
     * Convert using LibreOffice in headless mode
     */
    private byte[] convertUsingLibreOffice(byte[] excelData) throws IOException {
        // Create temporary files
        Path tempExcel = Files.createTempFile("excel_", ".xlsx");
        Path tempPdf = Files.createTempFile("pdf_", ".pdf");
        
        try {
            // Write Excel data to temp file
            Files.write(tempExcel, excelData);
            
            // Run LibreOffice conversion
            ProcessBuilder pb = new ProcessBuilder(
                "libreoffice",
                "--headless",
                "--convert-to", "pdf",
                "--outdir", tempPdf.getParent().toString(),
                tempExcel.toString()
            );
            
            pb.redirectErrorStream(true);
            Process process = pb.start();
            
            // Wait for conversion (max 30 seconds)
            boolean completed = process.waitFor(30, java.util.concurrent.TimeUnit.SECONDS);
            
            if (!completed || process.exitValue() != 0) {
                throw new IOException("LibreOffice conversion failed or timed out");
            }
            
            // Read generated PDF (LibreOffice creates file with same name but .pdf extension)
            String pdfFileName = tempExcel.getFileName().toString().replace(".xlsx", ".pdf");
            Path generatedPdf = tempPdf.getParent().resolve(pdfFileName);
            
            if (Files.exists(generatedPdf)) {
                return Files.readAllBytes(generatedPdf);
            } else {
                throw new IOException("PDF file not generated by LibreOffice");
            }
            
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException("Conversion interrupted", e);
        } finally {
            // Cleanup temp files
            Files.deleteIfExists(tempExcel);
            Files.deleteIfExists(tempPdf);
        }
    }
    
    /**
     * Check if LibreOffice is available
     */
    private boolean isLibreOfficeAvailable() {
        try {
            ProcessBuilder pb = new ProcessBuilder("libreoffice", "--version");
            Process process = pb.start();
            return process.waitFor(5, java.util.concurrent.TimeUnit.SECONDS) 
                   && process.exitValue() == 0;
        } catch (Exception e) {
            return false;
        }
    }
    
    /**
     * Create a PDF with instructions when conversion not available
     * Returns a simple instruction PDF using PDFBox (no LibreOffice needed)
     */
    private byte[] createInstructionPdf(byte[] excelData) throws IOException {
        // Alternative: Return the Excel data with instructions to convert manually
        // This way the endpoint doesn't fail - it returns useful information
        
        // Option 1: Throw exception (current behavior)
        throw new UnsupportedOperationException(
            "Excel-to-PDF conversion requires LibreOffice. " +
            "Install: apt-get install libreoffice-calc OR " +
            "use alternative: curl [same-endpoint-but-/generate] to get Excel file and convert manually."
        );
        
        // Option 2: Return Excel file (uncomment to enable)
        // return excelData; // Let client handle conversion
        
        // Option 3: Create instruction PDF with PDFBox (implement below)
        // return createSimpleInstructionPdfWithPdfBox(excelData);
    }
    
    /**
     * Optional: Create a simple instruction PDF using PDFBox
     * This doesn't require LibreOffice but provides a fallback
     */
    private byte[] createSimpleInstructionPdfWithPdfBox(byte[] excelData) throws IOException {
        // This could create a PDF that says:
        // "Excel-to-PDF conversion not available. 
        //  Download the Excel file separately and convert manually.
        //  Or install LibreOffice on the server."
        
        // For now, just throw - implement if needed
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    /**
     * Get information about available conversion methods
     */
    public ConversionInfo getConversionInfo() {
        boolean libreOfficeAvailable = isLibreOfficeAvailable();
        
        return new ConversionInfo(
            libreOfficeAvailable,
            libreOfficeAvailable ? "LibreOffice" : "None",
            !libreOfficeAvailable ? 
                "Install LibreOffice: apt-get install libreoffice-calc" : 
                "Ready to convert"
        );
    }
    
    /**
     * Information about conversion capabilities
     */
    public static class ConversionInfo {
        private final boolean available;
        private final String method;
        private final String message;
        
        public ConversionInfo(boolean available, String method, String message) {
            this.available = available;
            this.method = method;
            this.message = message;
        }
        
        public boolean isAvailable() { return available; }
        public String getMethod() { return method; }
        public String getMessage() { return message; }
    }
}
